### ISSUE TITLE
AI Planner for Game Environment Design

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-goal-task-planner#7]
### Describe the proposed feature and how it helps to overcome a problem or limitation

This proposal introduces a new AI planner that is designed to automate the process of creating apartment room designs in a magical college town setting for a game. The game is intended to be streamable on platforms like Twitch and Sammi. The current challenge lies in the manual effort and time required to design these rooms, which this AI planner aims to overcome.

### Other information about your context or usecase.

The AI planner will be utilized in a game development context. It will be responsible for creating engaging and visually appealing environments for a game set in a magical college town. These environments need to be designed keeping in mind the streaming aspect of the game on platforms like Twitch and Sammi.

### If known, describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams

The AI planner will leverage machine learning algorithms to generate room designs. These designs will be based on input parameters such as room size, style (e.g., modern, vintage), and function (e.g., study room, bedroom). 

Here's a simple pseudo-code example:

```python
def generateRoom(size, style, function):
    # Use ML model to generate room design
    roomDesign = mlModel.predict(size, style, function)
    return roomDesign
```

To facilitate the planning process, a preset of room designs will be created for the AI to refer to.

### Anything else

As we are still in the early stages of this project, any feedback or suggestions are welcome. We are particularly interested in ideas for features that would make the AI planner more useful or user-friendly.

**Comment by GeorgeS2019** [comment]
https://projects.laas.fr/planning/
![image](https://github.com/V-Sekai/godot-task-goal-planner/assets/49812372/5acaf7c2-c289-44f7-958b-93f5e5f41173)

**Comment by fire** [comment]
Paused for now.
